"""antonia-cognitive: DTOs y Protocols neutrales del contrato canónico (api-canonica v0.1).

Depende solo de pydantic y antonia-ontology. Los consumidores importan SOLO esta raíz.
"""

from cognitive._base import FrozenModel, freeze_json_snapshot
from cognitive._time import Utc
from cognitive.actions import (
    ActionError,
    ActionErrorCode,
    ActionExecutionStatus,
    ActionExecutionStore,
    ActionExecutor,
    ActionInvocation,
    ActionResult,
    ExecutionReservation,
    ImplementationBinding,
    ImplementationKind,
)
from cognitive.actors import (
    ActorBinding,
    ActorKind,
    ActorRegistry,
    ActorResult,
    ActorResultStatus,
    ActorRuntime,
    SelfAssignment,
    SelfAssignmentStore,
)
from cognitive.compiler import (
    GRAPH_EDGE_KINDS,
    EventTypeGraphDoc,
    GraphCompiler,
    GraphEdge,
    GraphEdgeKind,
    GuardGraphDoc,
    MachineGraph,
    MachineGraphDoc,
    StateGraphDoc,
    TransitionGraphDoc,
)
from cognitive.context import ContextProjector, ContextSnapshot, Snapshot, SnapshotBuilder
from cognitive.coordination import (
    CoordinationRuleDoc,
    Coordinator,
    DeliveryReport,
    DeliveryStatus,
    TargetResult,
    TargetSelector,
    TargetStatus,
)
from cognitive.errors import (
    AmbiguousTransition,
    AuthorizationDeniedError,
    CardinalityViolationError,
    CognitiveError,
    DefinitionMismatchError,
    EventCollisionError,
    GuardCompileError,
    GuardTypeError,
    IdempotencyCollisionError,
    InvalidEventError,
    RevisionConflictError,
    ScopeMismatchError,
    TransitionRejected,
    UnknownEventError,
    UnknownGuardOpError,
    UnreachableStateError,
)
from cognitive.events import Event, ExternalReceipt, Observation
from cognitive.goals import GoalAssessment, GoalEvidence, GoalInstance, GoalStatus, GoalStore
from cognitive.guards import (
    BOOL_OPS,
    COMPARISON_OPS,
    GUARD_OPS,
    GuardEvidence,
    GuardExpr,
    GuardOp,
)
from cognitive.jsons import JsonArray, JsonObject, JsonValue
from cognitive.knowledge import (
    KnowledgeActivation,
    KnowledgeActivationStatus,
    KnowledgeSelector,
    KnowledgeStore,
    KnowledgeVersion,
    KnowledgeVersionStatus,
)
from cognitive.machine import (
    Cardinality,
    MachineCommand,
    MachineDefinition,
    MachineInstance,
    StateDefinition,
    TimerSpec,
    TransitionDecision,
    TransitionDefinition,
    ValueBinding,
    machine_definition_hash,
    machine_definition_payload,
)
from cognitive.process import ProcessInstance, ProcessStore
from cognitive.repository import (
    InboxStore,
    MachineRepository,
    MachineTimerRepository,
    OutboxStore,
    ReceiptReservation,
    TimerRepository,
    WorldEvidenceRepository,
    invocation_fingerprint,
)
from cognitive.review import (
    ReviewRequest,
    ReviewRequestStatus,
    ReviewRequestStore,
    ReviewResolution,
)
from cognitive.scope import AccessScope, Scope
from cognitive.world import (
    DataCommand,
    DataOperation,
    EntityRegistry,
    EntitySchema,
    ExternalAdapter,
    ExternalKind,
    ExternalOperation,
    RetryPolicy,
    WorldData,
    WorldExternal,
)

__all__ = [
    "BOOL_OPS",
    "COMPARISON_OPS",
    "GRAPH_EDGE_KINDS",
    "GUARD_OPS",
    "AccessScope",
    "ActionError",
    "ActionErrorCode",
    "ActionExecutionStatus",
    "ActionExecutionStore",
    "ActionExecutor",
    "ActionInvocation",
    "ActionResult",
    "ActorBinding",
    "ActorKind",
    "ActorRegistry",
    "ActorResult",
    "ActorResultStatus",
    "ActorRuntime",
    "AmbiguousTransition",
    "AuthorizationDeniedError",
    "Cardinality",
    "CardinalityViolationError",
    "CognitiveError",
    "ContextProjector",
    "ContextSnapshot",
    "CoordinationRuleDoc",
    "Coordinator",
    "DataCommand",
    "DataOperation",
    "DefinitionMismatchError",
    "DeliveryReport",
    "DeliveryStatus",
    "EntityRegistry",
    "EntitySchema",
    "Event",
    "EventCollisionError",
    "EventTypeGraphDoc",
    "ExecutionReservation",
    "ExternalAdapter",
    "ExternalKind",
    "ExternalOperation",
    "ExternalReceipt",
    "FrozenModel",
    "GoalAssessment",
    "GoalEvidence",
    "GoalInstance",
    "GoalStatus",
    "GoalStore",
    "GraphCompiler",
    "GraphEdge",
    "GraphEdgeKind",
    "GuardCompileError",
    "GuardEvidence",
    "GuardExpr",
    "GuardGraphDoc",
    "GuardOp",
    "GuardTypeError",
    "IdempotencyCollisionError",
    "ImplementationBinding",
    "ImplementationKind",
    "InboxStore",
    "InvalidEventError",
    "JsonArray",
    "JsonObject",
    "JsonValue",
    "KnowledgeActivation",
    "KnowledgeActivationStatus",
    "KnowledgeSelector",
    "KnowledgeStore",
    "KnowledgeVersion",
    "KnowledgeVersionStatus",
    "MachineCommand",
    "MachineDefinition",
    "MachineGraph",
    "MachineGraphDoc",
    "MachineInstance",
    "MachineRepository",
    "MachineTimerRepository",
    "Observation",
    "OutboxStore",
    "ProcessInstance",
    "ProcessStore",
    "ReceiptReservation",
    "RetryPolicy",
    "ReviewRequest",
    "ReviewRequestStatus",
    "ReviewRequestStore",
    "ReviewResolution",
    "RevisionConflictError",
    "Scope",
    "ScopeMismatchError",
    "SelfAssignment",
    "SelfAssignmentStore",
    "Snapshot",
    "SnapshotBuilder",
    "StateDefinition",
    "StateGraphDoc",
    "TargetResult",
    "TargetSelector",
    "TargetStatus",
    "TimerRepository",
    "TimerSpec",
    "TransitionDecision",
    "TransitionDefinition",
    "TransitionGraphDoc",
    "TransitionRejected",
    "UnknownEventError",
    "UnknownGuardOpError",
    "UnreachableStateError",
    "Utc",
    "ValueBinding",
    "WorldData",
    "WorldEvidenceRepository",
    "WorldExternal",
    "freeze_json_snapshot",
    "invocation_fingerprint",
    "machine_definition_hash",
    "machine_definition_payload",
]
